server:
  port: 80
  sources:
    - path: /documents
    - path: /movies
    - path: /photos
      config:
        defaultEnabled: true
        
frontend:
  name: "Servidor-1"
auth:
  adminUsername: admin
  adminPassword: admin
  methods:
    password:
      enabled: true
      
integrations:
  media:
    ffmpegPath: "/usr/local/bin"
