server:
  port: 80
  sources:
    - path: /documents
      name: Documentos
    - path: /photos
      name: Fotos
    - path: /movies
      name: VÃ­deos
      config:
        defaultEnabled: true
        
frontend:
  name: "FileBrowser"
  
auth:
  adminUsername: admin
  adminPassword: admin
  methods:
    password:
      enabled: true
      
integrations:
  media:
    ffmpegPath: "/usr/local/bin"

